### ISSUE TITLE
MAF2MVF format for --sampletags

### ISSUE THREAD

**Issue by stsmall** [peaselab/mvftools#2]
Hi @jbpease,
I am trying to convert a MAF file to MVF. I cant seem to figure out the format of the --sampletags required option. It wasnt clear to me after reading the manual. Can you give me an example of the format for that option?
thanks,
@stsmall

python mvftools/mvftools.py ConvertMAF2MVF --maf RivD.maf.gz --out RivD.mvf --sampletags Amin.mini_7000000211273123:Amin                   

Traceback (most recent call last):
  File "mvftools/mvftools.py", line 1201, in <module>
    MVFcall(time0=TIME0)
  File "mvftools/mvftools.py", line 119, in __init__
    getattr(self, args.command)()
  File "mvftools/mvftools.py", line 447, in ConvertMAF2MVF
    maf2mvf(args)
  File "mvftools/pylib/mvfmaf.py", line 138, in maf2mvf
    samplelabels.remove(args.ref_tag)
ValueError: list.remove(x): x not in list

**Comment by jbpease** [comment]
Thanks for finding this.  We haven't been using MAF conversion much, so maintenance had fallen behind on this module. Should be working now and the documentation has been updated as well to make the command lines hopefully clearer.  For your syntax try "--sample-tags Amin:Amin,Afun:Afun,Agam:Agam,..."  .  also you'll now need --ref-tag specified to pick the reference genome sample.  The multple tags are also comma-separated now, consistent with style changes in other modules in the package.

Let me know if you have more issues and feel free to email a sample of the file, since sometimes there can be format variations that we are happy to try to accommodate.
